// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_404.tsx";
import * as $1 from "./routes/_app.tsx";
import * as $2 from "./routes/[name].tsx";
import * as $3 from "./routes/index.tsx";
import * as $$0 from "./islands/apps.tsx";
import * as $$1 from "./islands/docs.tsx";
import * as $$2 from "./islands/donate.tsx";
import * as $$3 from "./islands/policy.tsx";
import * as $$4 from "./islands/sites.tsx";
import * as $$5 from "./islands/chatbot.tsx";
import { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $0,
    "./routes/_app.tsx": $1,
    "./routes/[name].tsx": $2,
    "./routes/index.tsx": $3,
  },
  islands: {
    "./islands/apps.tsx": $$0,
    "./islands/docs.tsx": $$1,
    "./islands/donate.tsx": $$2,
    "./islands/policy.tsx": $$3,
    "./islands/sites.tsx": $$4,
    "./islands/chatbot.tsx": $$5,
  },
  baseUrl: import.meta.url,
};

export default manifest;
